Add DHADI group
NethServer/comps pull request #49
Opened 2020-11-02 15:38 UTC by gsanchietti

DAHDI is no more a dependency for freepbx package

NethServer/dev#6319

**Note**: remember to push translations to transifex after merge

2020-11-02 16:20 UTC, DavidePrincipi requested changes

2020-11-02 16:20 UTC, DavidePrincipi commented on updates-groups.xml.in
> +      <_name>DAHDI divers and tools</_name>
```suggestion
      <_name>DAHDI drivers and tools</_name>
```

2020-11-02 16:23 UTC, DavidePrincipi approved these changes

2020-11-03 10:49 UTC, Stell0 approved these changes

2020-11-17 09:13 UTC, Stell0 approved these changes

2020-11-17 16:36 UTC, merged